### ISSUE TITLE
Question About Conversion Results

### ISSUE THREAD

**Issue by damianoazzolini** [meelgroup/weighted-to-unweighted#1]
Hi,
I'm using this tool but the results of the computation is not clear to me. Consider the program shown in the README
```
$ cat my.cnf
p cnf 2 1
c ind 1 2 0
1 2 0
w 1 0.9
w 2 0.5
```
I convert it with the python script of this repo and I get as normalization factor  2^8.
After the conversion to UMC, I get (using [dsharp ](https://github.com/QuMuLab/dsharp) as model counter) 2^9 models.
So, 2^9/2^8 = 2.
However, If i use a weighted model counter, such as [ADDMC ](https://github.com/vardigroup/ADDMC) on the original WMC task, I get as result 0.95, wich is the value I expect. What are the reasons of such different results? The fact that the conversion from WMC to UMC is approximate? Or am I missing something? Even if I increase the precision with the flag `--prec`, I still get 2.

Thanks

**Comment by msoos** [comment]
Hi,

Something seems wrong on your end. Here is me using dhsharp on your CNF:

```
$ cat d.cnf
p cnf 2 1
c ind 1 2 0
1 2 0
w 1 0.9
w 2 0.5
$ ./weighted_to_unweighted.py d.cnf out
Header says vars: 2  maximum var used: 2
Orig vars: 2       Added vars: 7      
The resulting count you have to divide by: 2**8
Time to transform: 0.000 s

$ ./dsharp/dsharp out | grep "of solutions"
# of solutions:         243
```
Note that: `243/2**8=0.94921875`

Also, with GANAK:

```
$ ./old_ganak/build/ganak out | grep "pmc"
s pmc 243
```

Same, correct result.

I am closing this issue. However, if you find any other bug/misbehaviour/etc, please just open another issue. We are VERY happy to fix, advise, etc. However, this particular instance does not seem to be a bug.

Cheers and I hope you enjoy using the tool!

Mate
